### PR TITLE
Feature: OpenAI Key Extraction and Authentication

### LINKED ISSUE #11: Feature: OpenAI Key Abstraction
Abstracts API key using .env file, exports API key container.

### PR DESCRIPTION
**Pull request by Denisa-Iulia**
Abstracts API key using .env file, exports API key container.

### CODE REVIEW

**Comment by arudaev** [comment]
@Reptilian6163 is this OpenAI authentication, what exactly is this?

**Comment by arudaev** [comment]
You are doing `const OpenAI = require("openai");`. Did you run `npm install openai` and if so, did anything get added to package.json? @Reptilian6163

**Comment by Denisa-Iulia** [comment]
Yes, I did. The package-json file does have openai as a dependency. Should the dotenv package also be included in the dependency list?

Additionally, is this a good approach when using the key, authenticating in a separate file then using that file for the POST request? I'm still trying to understand how to use this authentication in the POST request file, for now. @HlexNC

**Comment by arudaev** [comment]
But did you commit package.json with the openai version you are using (not need to commit package-lock.json)

**Comment by arudaev** [comment]
The other thing, is that this API_key.js file is in the root of the project, when it should be inside `src/lib/openai_key.js` or `src/lib/openai_auth.js` smth

**Comment by arudaev** [comment]
> The other thing, is that this API_key.js file is in the root of the project, when it should be inside `src/lib/openai_key.js` or `src/lib/openai_auth.js` smth

And if it is a module, it should be exporting something. So that it can be used in other locations. On the other hand, if you want to have a single logic file, the name of the file should indicate it.  Notify me when you want me to approve the PR.

**Comment by arudaev** [comment]
@Reptilian6163

**Comment by arudaev** [comment]
Check out [README.md](https://github.com/THD-AI-2023/Devablos-Project?tab=readme-ov-file#project-structure)

**Comment by Denisa-Iulia** [comment]
I will take care of both files today. I will upload the package-json file when I think the other files can be merged, too.

**Pull request closed without merging**
